apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring-app
spec:
  template:
    spec:
      containers:
        - image: gcr.io/YOUR_PROJECT_ID/your-app
          ports:
            - containerPort: 8080