apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: app
          image: your-app:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app
spec:
  ports:
    - port: 8080
  selector:
    app: spring-app